### ISSUE TITLE
Template.instance() is null in template helper

### ISSUE THREAD

**Issue by gwendall** [sergeyt/meteor-typeahead#77] opened 2015-04-27 14:23 UTC
When using a template helper as described in [this example](https://github.com/sergeyt/meteor-typeahead#server-side-search), ``Template.instance()`` is ``null``.

```javascript
Template.demo.helpers({
  search: function(query, callback) {
    console.log("This is null", Template.instance());
  }
});
```
I would like to access it since I am using a local reactive variable to check whether the remote method i'm calling has finished loading or not. Any idea about why it is not available?

**Comment by sergeyt** [comment] 2015-04-27 15:23
@gwendall it seems PR #72 fixed the issue, but it is not release yet, could you please check whether the issue is reproducible with latest code.

**Comment by sergeyt** [comment] 2015-05-15 15:47
@gwendall please verify on v0.11.1 and close the issue if no repro

**Closed** 2015-07-05 09:19 UTC
